version: '1.0'
stages:
  - prepare   
  - build
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'austinlparker/helm-sample-app'
    revision: master
    git: github    
  MyAppDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: aparker/helm-sample-app-go
    working_directory: ./
    tag: ${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile  
    build_arguments:
      - SOURCE_FILE=slow
    on_success:
      metadata:
        set:
          - '${{MyAppDockerImage.imageId}}':
            - CF_QUALITY: true
            - Performance: true
            - Latency: ".89" 
            - Test_Coverage: "83%"
            - JIRA: "https://codefresh-io.atlassian.net/browse/MKTG-12"
  DeployMyChart:
    image: 'codefresh/cfstep-helm:3.0.3'
    title: Deploying Helm chart
    stage: deploy
    environment:
      - CHART_REF=charts/helm-example
      - RELEASE_NAME=my-go-chart-prod
      - KUBE_CONTEXT=${{KUBE_CONTEXT}}
      - VALUE_image_pullPolicy=Always
      - VALUE_image_tag=${{CF_SHORT_REVISION}}
      - VALUE_replicaCount=3
      - VALUE_buildID='${{CF_BUILD_ID}}'
      - VALUE_image_pullSecret=codefresh-generated-docker.io-dockerhub-default
      - VALUE_service_lsKey=${{LS_KEY}}
      - VALUE_service_version=${{CF_SHORT_REVISION}}
